### ISSUE TITLE
Validierung von Erscheinungsdatum funktioniert in ReaktivForms nicht!

### ISSUE THREAD

**Issue by HaedrichHC** [angular-buch/book-monkey4#4]
Hallo,

Die Validierung des Erscheinungsdatum im Formular (Iteration 4 - Reaktive-Forms) funktioniert nicht. Es wird keine Meldung angezeigt, nach dem zurücksetzen eines Datums im Formular "Erscheinungsdatum". 

In der BookFormComponent im FormBuilder "fb" fehlt im FormControl "published" als 2. Argument "Validators.required" (Zeile 58 - ../reactive-forms/book-form/book-form.component.ts)

Viele Grüße
Christian

**Comment by fmalcher** [comment]
Hallo Christian,
vielen Dank für dein Feedback! An der Stelle haben wir tatsächlich den Validator vergessen.
Den Code im Repo habe ich angepasst. Ich habe die Stelle außerdem in das Errata-Verzeichnis zur 3. Auflage aufgenommen, siehe https://github.com/angular-buch/website-articles/commit/a199eb4207d7c5e1a0360d452eff5d467940edc4 und https://angular-buch.com/blog/errata-3a

Viele Grüße
Ferdinand


// cc @JohannesHoppe @d-koppenhagen
